apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: groom-backend-hpa
  namespace: backend
spec:
  maxReplicas: 20
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment
    name: groom-backend-deployment
metrics:
- type: Resource
  resource:
    name: cpu
    target:
      type: Utilization
      averageUtilization: 30
