apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: groom-backend-hpa
  namespace: backend
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: groom-backend-deployment
  targetCPUUtilizationPercentage: 30
