apiVersion: v1
kind: Service
metadata:
  name: groom-backend-svc
  labels:
    run: groom-backend-svc
spec:
  type:  LoadBalancer    # 서비스 타입
  ports:
  - port: 8080       # 서비스 포트
    targetPort: 80   # 타켓, 즉 pod의 포트
    protocol: TCP
    name: http
  selector:
    app: backend
