
apiVersion: apps/v1           # 쿠버네티스 api 버전
kind: Deployment              # 생성할 오브젝트 종류
metadata:                
  name: groom-backend-deployment      # deployment의 이름
  labels:
    app: backend                # label 지정
spec:                         # deployment의 스펙을 정의
  replicas: {{ .hpa.minReplicas }}         # 3개의 pod 설정
  selector:                   # deployment가 관리할 pod를 찾는 방법을 정의
    matchLabels:     
      app: backend
  template:
    metadata:
      labels:                 # pod의 label
        app: backend
    spec:
      containers:             # 컨테이너 설정
      - name: backend          
        image: jeeseob/baromukja_backend:136
        ports:
        - containerPort: 9091
        resources:
          requests:
            cpu: "700m"
          limits:
            cpu: "1"
