apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: groom-backend-hpa
  namespace: backend
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: groom-backend-deployment
  targetCPUUtilizationPercentage: 70
