apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: groom-reservation-hpa
  namespace: backend
spec:
  maxReplicas: 10
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: groom-reservation-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30

