apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: groom-reservation-hpa
  namespace: backend
spec:
  maxReplicas: 10
  minReplicas: 5
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: groom-reservation-deployment
  targetCPUUtilizationPercentage: 30
