apiVersion: apps/v1           # 쿠버네티스 api 버전
kind: Deployment              # 생성할 오브젝트 종류
metadata:                
  name: groom-reservation-deployment      # deployment의 이름
  labels:
    app: reservation                # label 지정
spec:                         # deployment의 스펙을 정의
  # replicas: 5                 # 3개의 pod 설정
  selector:                   # deployment가 관리할 pod를 찾는 방법을 정의
    matchLabels:     
      app: reservation
  template:
    metadata:
      labels:                 # pod의 label
        app: reservation
    spec:
      containers:             # 컨테이너 설정
      - name: reservation          
        image: jeeseob/baromukja_backend_reservation:71
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: "300m"
          limits:
            cpu: "500m"
